// Types for static image imports (`import hero from './hero.jpg'`).
//
// Next writes the same reference into `next-env.d.ts`, but that file is
// generated by `next dev` / `next build` and gitignored, so a clean
// checkout running `tsc --noEmit` before the build (CI's typecheck step)
// has no declaration for `*.jpg` modules and fails with TS2307. Keeping
// the reference in a tracked file makes the typecheck independent of the
// build having run first.
/// <reference types="next/image-types/global" />
